export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg-page)",
    display: "flex",
    flexDirection: "column" as const,
  },
  topBar: {
    borderBottom: "1px solid var(--border)",
    background: "linear-gradient(180deg, #14141c 0%, #0c0c0f 100%)",
    position: "sticky" as const,
    top: 0,
    zIndex: 10,
  },
  topBarInner: {
    maxWidth: 1600,
    margin: "0 auto",
    padding: "16px 24px",
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    gap: 16,
  },
  playerHeader: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    justifyContent: "center",
  },
  bigAvatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dim) 100%)",
    color: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-head)",
    fontWeight: 700,
    fontSize: 20,
    letterSpacing: 1,
  },
  playerTitle: {
    fontFamily: "var(--font-head)",
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: 2,
    color: "var(--accent)",
    lineHeight: 1,
  },
  playerSub: {
    fontFamily: "var(--font-head)",
    fontSize: 11,
    letterSpacing: 3,
    color: "var(--text-sub)",
    marginTop: 3,
  },
  backBtn: {
    background: "transparent",
    border: "1px solid var(--border)",
    color: "var(--text-sub)",
    padding: "7px 16px",
    borderRadius: 6,
    fontFamily: "var(--font-head)",
    fontSize: 12,
    letterSpacing: 2,
    cursor: "pointer",
  },
  content: {
    maxWidth: 1600,
    margin: "0 auto",
    padding: "32px 24px",
    width: "100%",
  },
  section: { marginBottom: 40 },
  sectionTitle: {
    fontFamily: "var(--font-head)",
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: 3,
    color: "var(--text-sub)",
    marginBottom: 16,
    textTransform: "uppercase" as const,
  },
  sectionHint: {
    fontWeight: 400,
    fontSize: 12,
    letterSpacing: 1,
    color: "var(--text-muted)",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 14,
  },
  overviewCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius)",
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  overviewIcon: { fontSize: 18, marginBottom: 4 },
  overviewValue: {
    fontFamily: "var(--font-head)",
    fontSize: 26,
    fontWeight: 700,
    lineHeight: 1,
  },
  overviewLabel: {
    fontSize: 10,
    letterSpacing: 2,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    marginTop: 2,
  },
  summaryRow: { display: "flex", flexWrap: "wrap" as const, gap: 10 },
  summaryBadge: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 16px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 2,
    minWidth: 100,
  },
  summaryVal: {
    fontFamily: "var(--font-head)",
    fontSize: 22,
    fontWeight: 700,
    lineHeight: 1,
  },
  summaryLbl: {
    fontSize: 9,
    letterSpacing: 1.5,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
  },
  chartsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: 20,
  },
  chartCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-lg)",
    padding: "20px 16px",
  },
  tableWrap: {
    overflowX: "auto" as const,
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
  },
  table: { width: "100%", borderCollapse: "collapse" as const, fontSize: 13 },
  thead: { background: "var(--bg-surface)" },
  th: {
    padding: "10px 14px",
    textAlign: "left" as const,
    fontSize: 10,
    letterSpacing: 2,
    color: "var(--text-muted)",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    whiteSpace: "nowrap" as const,
    userSelect: "none" as const,
    borderBottom: "1px solid var(--border)",
  },
  trow: { borderBottom: "1px solid var(--border)" },
  td: {
    padding: "10px 14px",
    color: "var(--text)",
    whiteSpace: "nowrap" as const,
  },
  tdNum: {
    padding: "10px 14px",
    textAlign: "right" as const,
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap" as const,
  },
  mapCell: { display: "flex", alignItems: "center", gap: 8 },
  mapThumb: {
    width: 36,
    height: 24,
    objectFit: "cover" as const,
    borderRadius: 3,
    flexShrink: 0,
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginTop: 16,
  },
  pageBtn: {
    background: "transparent",
    border: "1px solid var(--border)",
    color: "var(--text-sub)",
    padding: "6px 14px",
    borderRadius: 6,
    fontFamily: "var(--font-head)",
    fontSize: 11,
    letterSpacing: 2,
    cursor: "pointer",
  },
  // ── Live preview ────────────────────────────────────────────────────────
  liveIdleWrap: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    padding: "80px 24px",
    color: "var(--text-muted)",
    textAlign: "center" as const,
  },
  liveIdleIcon: { fontSize: 48, opacity: 0.3 },
  liveIdleTitle: {
    fontFamily: "var(--font-head)",
    fontSize: 18,
    letterSpacing: 3,
    color: "var(--text-sub)",
    textTransform: "uppercase" as const,
  },
  liveIdleHint: { fontSize: 13, color: "var(--text-muted)", maxWidth: 400 },
  liveMapBanner: {
    position: "relative" as const,
    borderRadius: "var(--radius-lg)",
    overflow: "hidden",
    border: "1px solid var(--border)",
    marginBottom: 24,
    minHeight: 120,
    display: "flex",
    alignItems: "flex-end" as const,
  },
  liveMapBg: {
    position: "absolute" as const,
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover" as const,
    opacity: 0.35,
  },
  liveMapOverlay: {
    position: "relative" as const,
    zIndex: 1,
    padding: "20px 24px",
    width: "100%",
    display: "flex",
    alignItems: "flex-end" as const,
    justifyContent: "space-between" as const,
    flexWrap: "wrap" as const,
    gap: 12,
    background: "linear-gradient(to top, rgba(0,0,0,0.8) 0%, transparent 100%)",
  },
  liveMapName: {
    fontFamily: "var(--font-head)",
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: 2,
    color: "var(--accent)",
  },
  liveMapStats: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap" as const,
  },
  liveMapRecord: {
    fontFamily: "var(--font-head)",
    fontSize: 14,
    color: "var(--text-sub)",
    letterSpacing: 1,
  },
  wlChipRow: { display: "flex", gap: 4, alignItems: "center" },
  wlChip: (win: boolean) => ({
    width: 14,
    height: 14,
    borderRadius: 3,
    background: win ? "var(--green)" : "var(--red)",
    display: "inline-block" as const,
    flexShrink: 0,
  }),
  predictionBanner: (pct: number) => ({
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
    padding: "20px 28px",
    marginBottom: 24,
    background:
      pct >= 0.6
        ? "linear-gradient(135deg, rgba(5,139,190,0.15) 0%, var(--bg-card) 100%)"
        : pct >= 0.4
          ? "linear-gradient(135deg, rgba(250,191,43,0.12) 0%, var(--bg-card) 100%)"
          : "linear-gradient(135deg, rgba(201,37,65,0.15) 0%, var(--bg-card) 100%)",
    display: "flex",
    alignItems: "center",
    gap: 24,
  }),
  predictionPct: (pct: number) => ({
    fontFamily: "var(--font-head)",
    fontSize: 48,
    fontWeight: 700,
    lineHeight: 1,
    color: pct >= 0.6 ? "var(--green)" : pct >= 0.4 ? "var(--accent)" : "var(--red)",
    flexShrink: 0,
  }),
  predictionLabel: {
    fontFamily: "var(--font-head)",
    fontSize: 13,
    letterSpacing: 2,
    color: "var(--text-sub)",
    textTransform: "uppercase" as const,
  },
  predictionSub: { fontSize: 12, color: "var(--text-muted)", marginTop: 4 },
  liveGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
  liveTeamCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-lg)",
    overflow: "hidden",
  },
  liveTeamHeader: (friendly: boolean) => ({
    padding: "12px 16px",
    background: friendly ? "rgba(5,139,190,0.12)" : "rgba(201,37,65,0.12)",
    borderBottom: `1px solid ${friendly ? "rgba(5,139,190,0.25)" : "rgba(201,37,65,0.25)"}`,
    fontFamily: "var(--font-head)",
    fontSize: 12,
    letterSpacing: 3,
    color: friendly ? "var(--green)" : "var(--red)",
    textTransform: "uppercase" as const,
    display: "flex",
    alignItems: "center",
    gap: 8,
  }),
  livePlayerSlot: {
    padding: "12px 16px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  livePlayerSlotLast: {
    padding: "12px 16px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  livePlayerName: {
    fontFamily: "var(--font-head)",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text)",
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap" as const,
  },
  livePlayerUnknown: {
    fontFamily: "var(--font-head)",
    fontSize: 14,
    color: "var(--text-muted)",
    fontStyle: "italic",
  },
  liveBadge: (variant: "new" | "best" | "danger" | "you") => ({
    fontSize: 9,
    letterSpacing: 1.5,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    padding: "2px 6px",
    borderRadius: 4,
    background: variant === "new" ? "rgba(250,191,43,0.18)" : variant === "best" ? "rgba(5,139,190,0.18)" : variant === "danger" ? "rgba(201,37,65,0.18)" : "rgba(5,139,190,0.18)",
    color: variant === "new" ? "var(--accent)" : variant === "best" ? "var(--green)" : variant === "danger" ? "var(--red)" : "var(--accent)",
    border: `1px solid ${variant === "new" ? "rgba(250,191,43,0.35)" : variant === "best" ? "rgba(5,139,190,0.35)" : variant === "danger" ? "rgba(201,37,65,0.35)" : "rgba(5,139,190,0.35)"}`,
  }),
  livePlayerStats: {
    fontSize: 11,
    color: "var(--text-muted)",
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  liveStatVal: { color: "var(--text-sub)", fontVariantNumeric: "tabular-nums" },
} as const;
