export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg-page)",
    display: "flex",
    flexDirection: "column" as const,
  },
  topBar: {
    borderBottom: "1px solid var(--border)",
    background: "linear-gradient(180deg, #14141c 0%, #0c0c0f 100%)",
    position: "sticky" as const,
    top: 0,
    zIndex: 10,
  },
  topBarInner: {
    maxWidth: 1600,
    margin: "0 auto",
    padding: "16px 24px",
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    gap: 16,
  },
  playerHeader: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    justifyContent: "center",
  },
  bigAvatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dim) 100%)",
    color: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-head)",
    fontWeight: 700,
    fontSize: 20,
    letterSpacing: 1,
  },
  playerTitle: {
    fontFamily: "var(--font-head)",
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: 2,
    color: "var(--accent)",
    lineHeight: 1,
  },
  playerSub: {
    fontFamily: "var(--font-head)",
    fontSize: 11,
    letterSpacing: 3,
    color: "var(--text-sub)",
    marginTop: 3,
  },
  backBtn: {
    background: "transparent",
    border: "1px solid var(--border)",
    color: "var(--text-sub)",
    padding: "7px 16px",
    borderRadius: 6,
    fontFamily: "var(--font-head)",
    fontSize: 12,
    letterSpacing: 2,
    cursor: "pointer",
  },
  content: {
    maxWidth: 1600,
    margin: "0 auto",
    padding: "32px 24px",
    width: "100%",
  },
  section: { marginBottom: 40 },
  sectionTitle: {
    fontFamily: "var(--font-head)",
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: 3,
    color: "var(--text-sub)",
    marginBottom: 16,
    textTransform: "uppercase" as const,
  },
  sectionHint: {
    fontWeight: 400,
    fontSize: 12,
    letterSpacing: 1,
    color: "var(--text-muted)",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 14,
  },
  overviewCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius)",
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  overviewIcon: { fontSize: 18, marginBottom: 4 },
  overviewValue: {
    fontFamily: "var(--font-head)",
    fontSize: 26,
    fontWeight: 700,
    lineHeight: 1,
  },
  overviewLabel: {
    fontSize: 10,
    letterSpacing: 2,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    marginTop: 2,
  },
  summaryRow: { display: "flex", flexWrap: "wrap" as const, gap: 10 },
  summaryBadge: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 16px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 2,
    minWidth: 100,
  },
  summaryVal: {
    fontFamily: "var(--font-head)",
    fontSize: 22,
    fontWeight: 700,
    lineHeight: 1,
  },
  summaryLbl: {
    fontSize: 9,
    letterSpacing: 1.5,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
  },
  chartsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: 20,
  },
  chartCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-lg)",
    padding: "20px 16px",
  },
  tableWrap: {
    overflowX: "auto" as const,
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--border)",
  },
  table: { width: "100%", borderCollapse: "collapse" as const, fontSize: 13 },
  thead: { background: "var(--bg-surface)" },
  th: {
    padding: "10px 14px",
    textAlign: "left" as const,
    fontSize: 10,
    letterSpacing: 2,
    color: "var(--text-muted)",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    whiteSpace: "nowrap" as const,
    userSelect: "none" as const,
    borderBottom: "1px solid var(--border)",
  },
  trow: { borderBottom: "1px solid var(--border)" },
  td: {
    padding: "10px 14px",
    color: "var(--text)",
    whiteSpace: "nowrap" as const,
  },
  tdNum: {
    padding: "10px 14px",
    textAlign: "right" as const,
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap" as const,
  },
  mapCell: { display: "flex", alignItems: "center", gap: 8 },
  mapThumb: {
    width: 36,
    height: 24,
    objectFit: "cover" as const,
    borderRadius: 3,
    flexShrink: 0,
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginTop: 16,
  },
  pageBtn: {
    background: "transparent",
    border: "1px solid var(--border)",
    color: "var(--text-sub)",
    padding: "6px 14px",
    borderRadius: 6,
    fontFamily: "var(--font-head)",
    fontSize: 11,
    letterSpacing: 2,
    cursor: "pointer",
  },
} as const;
