// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  WinEnum,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  playerName: __t.string().name("player_name"),
  detectionTime: __t.string().name("detection_time"),
  map: __t.option(__t.string()),
  similarityScore: __t.f32().name("similarity_score"),
  combatScore: __t.option(__t.i32()).name("combat_score"),
  objectiveScore: __t.option(__t.i32()).name("objective_score"),
  supportScore: __t.option(__t.i32()).name("support_score"),
  eliminations: __t.option(__t.i32()),
  assists: __t.option(__t.i32()),
  deaths: __t.option(__t.i32()),
  revives: __t.option(__t.i32()),
  objectives: __t.option(__t.i32()),
  get win() {
    return WinEnum;
  },
});
