// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const MatchEntry = __t.object("MatchEntry", {
  id: __t.u64(),
  playerName: __t.string(),
  detectionTime: __t.string(),
  map: __t.option(__t.string()),
  similarityScore: __t.f32(),
  combatScore: __t.option(__t.i32()),
  objectiveScore: __t.option(__t.i32()),
  supportScore: __t.option(__t.i32()),
  eliminations: __t.option(__t.i32()),
  assists: __t.option(__t.i32()),
  deaths: __t.option(__t.i32()),
  revives: __t.option(__t.i32()),
  objectives: __t.option(__t.i32()),
  get win() {
    return WinEnum;
  },
});
export type MatchEntry = __Infer<typeof MatchEntry>;

export const MatchPlayer = __t.object("MatchPlayer", {
  id: __t.u64(),
  matchId: __t.u64(),
  name: __t.string(),
  friendly: __t.bool(),
});
export type MatchPlayer = __Infer<typeof MatchPlayer>;

export const Player = __t.object("Player", {
  name: __t.string(),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `WinEnum`.
export const WinEnum = __t.enum("WinEnum", {
  Win: __t.unit(),
  Loss: __t.unit(),
  Undefined: __t.unit(),
});
export type WinEnum = __Infer<typeof WinEnum>;

