// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.u64(),
  map: __t.string(),
  win: __t.bool(),
  combatScore: __t.i32(),
  objectiveScore: __t.i32(),
  supportScore: __t.i32(),
  eliminations: __t.i32(),
  assists: __t.i32(),
  deaths: __t.i32(),
  revives: __t.i32(),
  objectives: __t.i32(),
};
